### PR TITLE
Update to 0.5.0

### PR DESCRIPTION
**Pull request by jasongrout**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by jasongrout** [comment]
@vidartf, I also added myself as a maintainer of the conda-forge package. Please let me know if you want me to take myself off.

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Comment by vidartf** [comment]
It looks like an issue is that `npm`/`node` is not available on the build machines. The recipe as it is now rebuilds the wheel, so it would need those to be present.

**Comment by jasongrout** [comment]
@vidartf - the tests are passing now.

**Review by vidartf — APPROVED** [review]

**Pull request merged**
